#!/usr/bin/env bash
# Ejecutar en: SERVIDOR WEB (Ubuntu) con sudo
# Instala Apache con HTTPS (certificado autofirmado) y OpenSSH
set -e
[ "$EUID" -ne 0 ] && { echo "Ejecuta con sudo"; exit 1; }
 
apt update
apt install -y apache2 openssh-server openssl
 
a2enmod ssl
mkdir -p /etc/ssl/2241
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout /etc/ssl/2241/server.key -out /etc/ssl/2241/server.crt \
  -subj "/C=DO/O=Infraestructura3/CN=10.22.41.130"
 
cat > /etc/apache2/sites-available/https-2241.conf << 'CONF'
<VirtualHost *:443>
    ServerName 10.22.41.130
    DocumentRoot /var/www/html
    SSLEngine on
    SSLCertificateFile    /etc/ssl/2241/server.crt
    SSLCertificateKeyFile /etc/ssl/2241/server.key
</VirtualHost>
CONF
 
echo "<h1>Servidor Web - Matricula 20252241</h1>" > /var/www/html/index.html
a2ensite https-2241
systemctl enable --now apache2 ssh
systemctl reload apache2
 
echo "=== Servicios escuchando ==="
ss -tlnp | grep -E ':(22|443)\b'
systemctl is-active apache2 ssh
 
